---
on:
  push:
    branches: master
name: Build and publish
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # Map a step output to a job output
    steps:
      - name: Install packages
        run: npm install
      - name: build project
        run: env FRAMER_TOKEN=${{ secrets.FRAMER_TOKEN }} npx framer-cli build ./design-system.framerfx
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: env FRAMER_TOKEN=${{ secrets.FRAMER_TOKEN }} npx framer-cli publish ./design-system.framerfx --public --yes


